name: Angular GitHub CI
on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.FM_DOCKER_USERNAME }} -p ${{ secrets.FM_DOCKER_PASSWORD }}    
#      - name: Build frontend Docker image
#        run: docker build -t ${{ secrets.FM_DOCKER_USERNAME }}/photobooth-frontend:${GITHUB_SHA} -f photobooth-frontend/Dockerfile ./photobooth-frontend
#      - name: Push frontend Docker image to Docker Hub
#        run: docker push ${{ secrets.FM_DOCKER_USERNAME }}/photobooth-frontend:${GITHUB_SHA}
      - name: Build backend Docker image
        run: docker build -t ${{ secrets.FM_DOCKER_USERNAME }}/photobooth-backend:${GITHUB_SHA} -f photobooth-backend/Dockerfile ./photobooth-backend
      - name: Push backend Docker image to Docker Hub
        run: docker push ${{ secrets.FM_DOCKER_USERNAME }}/photobooth-backend:${GITHUB_SHA}
